version: '3'

services:
  db:
    restart: ${RESTART_DB-always}
    image: postgres
    volumes: ["./database:/var/lib/postgresql/data"]
    ports: ["5432:5432"]
    dns:
      - ${DNS_1}
      - ${DNS_2}
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    restart: ${RESTART_WEB-always}
    image: concourse/concourse
    command: web
    links: [db]
    depends_on: [db]
    ports: ["8080:8080"]
    dns:
      - ${DNS_1}
      - ${DNS_2}
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_EXTERNAL_URL: ${CONCOURSE_EXTERNAL_URL}
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: ${CONCOURSE_POSTGRES_PASSWORD}
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_GITHUB_CLIENT_ID: ${CONCOURSE_GITHUB_CLIENT_ID}
      CONCOURSE_GITHUB_CLIENT_SECRET: ${CONCOURSE_GITHUB_CLIENT_SECRET}
      CONCOURSE_MAIN_TEAM_GITHUB_ORG: alaress
      CONCOURSE_ADD_LOCAL_USER: test:${CONCOURSE_ADD_LOCAL_USER_PASS}
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: "false"
      CONCOURSE_GARDEN_DNS_SERVER: ${DNS_1}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker:
    restart: ${RESTART_WORKER-always}
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [web]
    dns:
      - ${DNS_1}
      - ${DNS_2}
    volumes: ["./keys/worker:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: "false"
      CONCOURSE_GARDEN_DNS_SERVER: ${DNS_1}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
