version: '3'

services:
  db:
    restart: always
    image: postgres
    volumes: ["./database:/var/lib/postgresql/data"]
    ports: ["5432:5432"]
    dns:
      - ${DNS_1}
      - ${DNS_2}
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass
      PGDATA: /var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    restart: always
    image: concourse/concourse
    command: web
    links: [db]
    depends_on: [db]
    ports: ["8080:8080"]
    dns:
      - ${DNS_1}
      - ${DNS_2}
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker:
    restart: always
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [web]
    dns:
      - ${DNS_1}
      - ${DNS_2}
    volumes: ["./keys/worker:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
